version: "3.8"

services:
  postgres:
    container_name: db
    image: postgres:16.0
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 2

  event-app:
    build: .
    container_name: event-app
    image: event-app
    ports:
      - "8000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"