spring.application.name: event-app

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  flyway:
    baselineOnMigrate: true
  mail:
    host: smtp.mail.ru
    port: 465
    username: username # нерабочая конфигурация, нужны реальные имя и пароль в env
    password: password # обращаться за данными к @alex_darklol
#    username: ${EMAIL_USERNAME}
#    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

minio:
  url: http://localhost:9000
  accessKey: minio-admin
  secretKey: minio-admin

springdoc:
  api-docs:
    path: /event-app/v3/api-docs
  swagger-ui:
    path: /event-app/api

notifications:
  cron:
    create-notification-job: '0 0/15 * * * *' # каждая 15-я минута часа -- для подробностей смотри https://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html
    sending-period-in-minutes: 15 # это число должно совпадать с частотой срабатывания выражения выше, инче будем отслылать дубликаты
  taskUrl: 'http://localhost:8080/task/'
